spring:
  datasource:
    # 1. MySQL 드라이버 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 2. 방금 워크벤치에서 만든 스키마 이름을 localhost:3306/ 뒤에 적으세요!
    url: jdbc:mysql://localhost:3306/backend_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    # 3. MySQL 설치 시 설정한 아이디와 비밀번호
    username: root
    password: 1234

jwt:
  issuer: studyjohnasilta
  secret_key: studyjohnasilta_secret_key_for_sibal_project_2026_safe_and_strong

