name: React Build and Deploy

on:
  push:
    branches: ["CICD"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./services/react_sample

      - name: Build the React app
        run: npm run build
        working-directory: ./services/react_sample

      - name: debug
        run: |
          ls -la
          cd ./services
          ls -la
          cd react_sample
          ls -la
          cd dist
          ls -la

      #- name: Change Directory
      #  run: cd ./services/react_sample/dist

      - name: for debugging
        run: |
          ls -la
          cat index.html

      - name: Upload dist to Server via SSH
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          source: "./*"
          target: "/srv/www/html/lanovel"