name: Deploy Backend

on:
  push:
    branches: ['spring-deploy-actions']


jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6    
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: make build directory
        run: mkdir -p ./services/backend/dist

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./services/backend/gradlew

      - name: Build with Gradle
        run: ./gradlew :build
        working-directory: ./services/backend
    
      - name: debug
        run: ls -al ./services/backend/dist

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.19.2
        with:
          context: ./services/backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest