name: Deploy Backend

on:
  push:
    branches: ['spring-deploy-actions']

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6    

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: make build directory
        run: mkdir -p ./services/backend/dist

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./services/backend/gradlew

      - name: Build with Gradle
        run: ./gradlew :build
        working-directory: ./services/backend

      - name: Copy JAR to dist
        run: |
          mkdir -p services/backend/dist
          cp services/backend/build/libs/*.jar services/backend/dist/
    
      - name: debug
        run: ls -al ./services/backend/dist

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Lowercase Owner, Repository Name
        run: |
          echo "REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "TAG=latest" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.19.2
        with:
          context: ./services/backend
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /srv/lanovel-backend
            docker pull ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}
            docker stop lanovel-backend || true
            docker rm lanovel-backend || true
            docker run -d --name lanovel-backend -p 8080:8080 ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG }}